// 本檔案由 scripts/generate-icon-names.ts 自動產生，請勿手動修改。

export const ICON_NAMES = [
  'alert-circle',
  'alert-triangle',
  'arrow-left-right',
  'calendar',
  'check',
  'check-circle',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevrons-left',
  'chevrons-right',
  'close',
  'dice',
  'dice-20',
  'download',
  'edit',
  'external-link',
  'eye',
  'eye-off',
  'grid',
  'hamburger',
  'heal',
  'heptagram',
  'hurt',
  'info',
  'list',
  'minus',
  'plus',
  'profile',
  'search',
  'star',
  'swipe-up',
  'tool',
  'trash',
  'upload',
  'user',
] as const

export type IconName = (typeof ICON_NAMES)[number]
